#!/bin/bash

# Build docker image
git clone https://github.com/colonyamerican/dokku-pg-dockerfiles /tmp/dokku-pg-dockerfiles
docker build -q=true -t colonyamerican/postgresql /tmp/dokku-pg-dockerfiles
rm -rf /tmp/dokku-pg-dockerfiles
